### PR TITLE
Andrew/build overhaul

### PR DESCRIPTION
**Pull request by ayjayt**
~Two~ Too many goals:
- [x] shore up education
  - [x] reread windows buiid
  - [x] reread linux build
  - [x] reread mac build
  - [x] whats going on with docker
  - Notes:
    - Linux is also copying over .so files, which is... unfortunate (was there no easy way to switch to static?): Other people working on chromium have other solutions, which seem to align more with google: https://github.com/ungoogled-software/ungoogled-chromium/pull/649/files, https://github.com/ungoogled-software/ungoogled-chromium/pull/649, https://github.com/ungoogled-software/ungoogled-chromium/issues/556, https://chromium.googlesource.com/chromium/src/+/master/docs/linux_sysroot.md
    - More information: https://chromium.googlesource.com/chromium/src/+/master/docs/component_build.md (can check with `ldd` and `otool -L`)
    - https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md#Setting-up-the-build
    - We were just half-building in docker for some reason
  - [x] whats going on with packaging
- [x] document and get rid of weird bin builder, just add it to docs 
- [x] make default source file for arch and cpus
- [x] command to run them all
- [x] make set_version # choose chromium version, choose platform, everything else is auto
- [x] make fetch_tools # git clone depot_tools
- [x] deal with spaces
- [x] add verbose flags
- [x] add latest flag
- [x] get os/architecture
- [x] utilities namespace
- [x] test with circle ci, reconfigure
- [x] update template
- [x] Get docker dockering
- [x] add docker and all to bin
- [x] stages to src
- [ ] finish init_tools #  look at note in fetch_chromium.ps1, info changes based on version/platform?
    - [x] check get build dependencies
    - [x] read them
    - [x] run on linux
    - [x] get on windows
    - [x] run on windows
    - [ ] run on mac
    - [ ] run on circle ci
    - [ ] test new 126 on windows
- [ ] start description doc
- [x] make sync # runs gclient
  - [x] why did we need gclient?- we don't use fetch since it pulls too much
  - [x] reread fetch script above to see if it accepts other arguments now
  - [x] build_deps.sh may work instead of make init_tools
- [x] make gen_meta # CREDITS, license.py, version, README, etc
- [x] make patch # runs patches based on versions
- [x] make config_build # appends kaleido instructions to `BUILD.gn`, runs `gn gen out`
- [x] need to specify target arch
- [x] make compile # runs ninja
- [x]  END THIS PR THERE
   - [x] remove all old scripts
   - [x] fix up readmes

### CODE REVIEW

**Comment by ayjayt** [comment]
- [ ] circleci is just turned off completely, need to figure out how to turn it on for master + all pull requests

**Comment by ayjayt** [comment]
Just marked as ready for review to see if it will build on circle-ci

**Comment by ayjayt** [comment]
Attaching some notes to make it into the docs:

- Build split is in process, can't assume (don't want to) shared execution environment, so we use temp files/cache to communicate between parts of the process
- CircleCI should not contain much logic except:
  - Specifying build environment
  - Installing build *system* dependencies (git, bash, rsync, etc)- not build dependencies, ie not shared libraries (windows sdk)
  - Flags for cross compiling (really no way around this if we're tyring to save money)

**Comment by ayjayt** [comment]
The code itself here is ready for review, but it may be easier for the reviews to wait until after I do a documentation run.

**Comment by gvwilson** [comment]
I propose closing this PR but keeping the branch cc @ayjayt

**Pull request closed without merging**
